version: '3.7'
services:
  altitude-scraper:
    build: ./web_scraper
    container_name: bookings_scraper_cron
    volumes:
      - ./:/workspace/
    command: cron && tail -f /workspace/logs/cron.log
  # dev:
  #   build: ./
  #   container_name: climb_dev
  #   volumes:
  #     - ./:/workspace/