version: '3.7'
services:
  climbr_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: climbr_es
    environment:
      - node.name=climbr_es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=climbr_es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
  climbr_kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: climbr_kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://climbr_es:9200
      ELASTICSEARCH_HOSTS: http://climbr_es:9200
    depends_on:
      - climbr_es
    restart: always
  climbr_cli:
    build: ./docker/cli
    container_name: climbr_cli
    volumes:
      - ./:/workspace/
    depends_on:
      - climbr_kibana
    restart: always
  climbr_bookings:
    build:
      context: .
      dockerfile: ./docker/webscraper/dockerfile
    container_name: climbr_bookings
    network_mode: "host"
    volumes:
      - ./:/workspace/
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - CLIMBR_EMAIL=${CLIMBR_EMAIL}
      - CLIMBR_PASS=${CLIMBR_PASS}
    profiles:
      - webscraper
volumes:
  data01:
    driver: local
