# Standardized container to track and development enviroment
FROM ubuntu
ENV DOCKER=true
ENV TZ=America/Toronto
ENV DISPLAY=:99
ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir /workspace /workspace/logs/ /workspace/logs/cli/
WORKDIR /workspace
RUN apt-get -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install python3 python3-pip \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf /usr/bin/pip3 /usr/bin/pip \
    && pip install poetry==1.1.7 \
    && apt-get update
ENTRYPOINT ["/bin/bash", "./docker/cli/entrypoint.sh"]