# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Nox Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.6"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.7
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Run Nox
      run: poetry run nox